---
# tasks file for ambalabanov.lvm

- name: partition created
  parted:
    device: "{{ dpath }}"
    number: 1
    state: present
  when: dname in ansible_devices
  register: parted

- name: volume group created
  lvg:
    vg: "{{ vgname }}"
    pvs: 
     - "{{ vgpath }}"
    pesize: 8M
  when: parted.partitions is defined

- name: gather facts
  gather_facts:
    parallel: yes

- name: logical volume created
  lvol:
    vg: "{{ vgname }}"
    lv: "{{ lvname }}"
    size: 100%FREE
  when:
    - vgname in ansible_lvm['vgs']
    - lvname not in ansible_lvm['lvs']

- name: gather facts
  gather_facts:
    parallel: yes

- name: filesystem configured
  block:
    - name: filesystem created
      filesystem:
        fstype: xfs
        dev: /dev/{{ vgname }}/{{ lvname }}
    
    - name: mount point present
      file:
        path: "{{ mpath }}"
        state: directory

    - name: filesystem mounted
      mount:
        path: "{{ mpath }}"
        src: /dev/{{ vgname }}/{{ lvname }}
        fstype: xfs
        state: mounted
  when: lvname in ansible_lvm['lvs']