---
- name: configure repo
  hosts: master
  vars:
    mount_point: /media
    conf_file: /etc/httpd/conf.d/repo.conf
    packages:
      - firewalld
      - httpd
  tasks:
    - name: mount DVD
      mount:
        src: /dev/cdrom
        path: "{{ mount_point }}"
        fstype: iso9660
        state: mounted

    - name: packages installed
      yum:
        name: "{{ packages }}"
        state: present

    - name: service started & enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: 
        "{{ packages }}"
    
    - name: firewall configured
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes
    
    - name: test page created
      copy:
        content: "welcome on board\n"
        dest: /var/www/html/index.html
    
    - name: httpd configured
      template:
        src: templates/repo.conf.j2
        dest: "{{ conf_file }}"
      notify: restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted

- name: add  repos
  hosts: node
  tasks:
    - name: http open
      uri:
        url: http://master.example.com/repo/BaseOS/repodata/repomd.xml
        
    - name: BaseOS repo added
      yum_repository:
        name: BaseOS
        description: RHEL 8.4 BaseOS (DVD)
        baseurl: http://master.example.com/repo/BaseOS/
        enabled: yes
        gpgcheck: yes
        state: present

    - name: AppStream  repo added
      yum_repository:
        name: AppStream
        description: RHEL 8.4 AppStream (DVD)
        baseurl: http://master.example.com/repo/AppStream/
        enabled: yes
        gpgcheck: yes
        state: present
        

