---
- name: Configure haproxy
  hosts: proxy
  vars:
    haproxy_backend_servers:
      - name: app1
        address: "{{ groups['web'][0]}}:80"
      - name: app2
        address: "{{ groups['web'][1]}}:80"
  roles:
    - role: geerlingguy.haproxy
  post_tasks:
    - name: firewalld configured
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes