---
- name: rollback master
  hosts: master
  become: yes
  tasks:
    - name: ansible repo disabled
      rhsm_repository:
        name: ansible-2-for-rhel-8-x86_64-rpms
        state: disabled       
    - name: unregister
      redhat_subscription:
        state: absent
    - name: ansible removed
      yum:
        name: 
          - ansible
          - rhel-system-roles
        state: absent