---
- name: rollback all
  hosts: all
  remote_user: vagrant
  become: yes
  vars:
    username: devops
  tasks:
    - name: user deleted
      user:
        name: "{{ username  }}"
        state: absent
        remove: yes
        force: yes

    - name: sudoers deleted
      file:
        path: "/etc/sudoers.d/{{ username  }}"
        state: absent
